/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  ImgData,
} from '@src/cnst/images';

export namespace Components {
  interface AppFooter {}
  interface AppHeader {}
  interface AppImages {
    'imgs': ImgData[];
    'maxHeight': number;
  }
  interface AppRoot {}
  interface ContactPage {}
  interface HomePage {
    'segment': string;
  }
}

declare global {


  interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {}
  var HTMLAppFooterElement: {
    prototype: HTMLAppFooterElement;
    new (): HTMLAppFooterElement;
  };

  interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {}
  var HTMLAppHeaderElement: {
    prototype: HTMLAppHeaderElement;
    new (): HTMLAppHeaderElement;
  };

  interface HTMLAppImagesElement extends Components.AppImages, HTMLStencilElement {}
  var HTMLAppImagesElement: {
    prototype: HTMLAppImagesElement;
    new (): HTMLAppImagesElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLContactPageElement extends Components.ContactPage, HTMLStencilElement {}
  var HTMLContactPageElement: {
    prototype: HTMLContactPageElement;
    new (): HTMLContactPageElement;
  };

  interface HTMLHomePageElement extends Components.HomePage, HTMLStencilElement {}
  var HTMLHomePageElement: {
    prototype: HTMLHomePageElement;
    new (): HTMLHomePageElement;
  };
  interface HTMLElementTagNameMap {
    'app-footer': HTMLAppFooterElement;
    'app-header': HTMLAppHeaderElement;
    'app-images': HTMLAppImagesElement;
    'app-root': HTMLAppRootElement;
    'contact-page': HTMLContactPageElement;
    'home-page': HTMLHomePageElement;
  }
}

declare namespace LocalJSX {
  interface AppFooter {}
  interface AppHeader {}
  interface AppImages {
    'imgs'?: ImgData[];
    'maxHeight'?: number;
  }
  interface AppRoot {}
  interface ContactPage {}
  interface HomePage {
    'segment'?: string;
  }

  interface IntrinsicElements {
    'app-footer': AppFooter;
    'app-header': AppHeader;
    'app-images': AppImages;
    'app-root': AppRoot;
    'contact-page': ContactPage;
    'home-page': HomePage;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-footer': LocalJSX.AppFooter & JSXBase.HTMLAttributes<HTMLAppFooterElement>;
      'app-header': LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
      'app-images': LocalJSX.AppImages & JSXBase.HTMLAttributes<HTMLAppImagesElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'contact-page': LocalJSX.ContactPage & JSXBase.HTMLAttributes<HTMLContactPageElement>;
      'home-page': LocalJSX.HomePage & JSXBase.HTMLAttributes<HTMLHomePageElement>;
    }
  }
}


